export const FETCH_DATA_LIST_REQUEST = 'FETCH_DATA_LIST_REQUEST';
export const FETCH_DATA_LIST_SUCCESS = 'FETCH_DATA_LIST_SUCCESS';
export const FETCH_DATA_LIST_FAILURE = 'FETCH_DATA_LIST_FAILURE';
export const SEARCH_DATA_LIST_REQUEST = 'SEARCH_DATA_LIST_REQUEST';
export const SEARCH_DATA_LIST_SUCCESS = 'SEARCH_DATA_LIST_SUCCESS';
export const SEARCH_DATA_LIST_FAILURE = 'SEARCH_DATA_LIST_FAILURE';
