export const FETCH_DATA_LIST_REQUEST = 'FETCH_DATA_LIST_REQUEST';
export const FETCH_DATA_LIST_SUCCESS = 'FETCH_DATA_LIST_SUCCESS';
export const FETCH_DATA_LIST_FAILURE = 'FETCH_DATA_LIST_FAILURE';
export const UPDATE_SELECTED_LIST = 'UPDATE_SELECTED_LIST';
export const UPDATE_VISIBLE_LIST = 'UPDATE_VISIBLE_LIST';
